const nodemailer = require("nodemailer");
const { formatRequestType } = require("../utils/requestType");

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

const sendApprovalEmail = async (request) => {
  const approveLink = `http://localhost:3000/requests/${request.id}/approve-link`;
  const rejectLink = `http://localhost:3000/requests/${request.id}/reject-link`;

  await transporter.sendMail({
    from: process.env.EMAIL_USER,
    to: process.env.EMAIL_USER,
    subject: `Approval Required: ${request.title}`,
    html: `
  <div style="font-family: Arial, sans-serif; background-color: #f3f4f6; padding: 30px;">
    <div style="max-width: 640px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; overflow: hidden; border: 1px solid #e5e7eb;">
      
      <div style="background-color: #111827; color: white; padding: 22px 28px;">
        <h2 style="margin: 0;">Approval Required</h2>
        <p style="margin: 6px 0 0; color: #d1d5db;">
          A new internal request is waiting for review.
        </p>
      </div>

      <div style="padding: 28px;">
        <p style="font-size: 16px; margin-top: 0;">
          Please review the following request:
        </p>

        <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
          <tr>
            <td style="padding: 10px; font-weight: bold; color: #374151; width: 140px;">Title</td>
            <td style="padding: 10px; color: #111827;">${request.title}</td>
          </tr>
          <tr>
            <td style="padding: 10px; font-weight: bold; color: #374151;">Type</td>
            <td style="padding: 10px; color: #111827;">${formatRequestType(request.requestType)}</td>
          </tr>
          <tr>
            <td style="padding: 10px; font-weight: bold; color: #374151;">Requested By</td>
            <td style="padding: 10px; color: #111827;">${request.requestedBy}</td>
          </tr>
          <tr>
            <td style="padding: 10px; font-weight: bold; color: #374151;">Description</td>
            <td style="padding: 10px; color: #111827;">${request.description}</td>
          </tr>
        </table>

        <div style="margin-top: 28px;">
          <a href="${approveLink}" 
             style="display: inline-block; background-color: #16a34a; color: white; text-decoration: none; padding: 12px 18px; border-radius: 8px; font-weight: bold; margin-right: 10px;">
            Approve Request
          </a>

          <a href="${rejectLink}" 
             style="display: inline-block; background-color: #dc2626; color: white; text-decoration: none; padding: 12px 18px; border-radius: 8px; font-weight: bold;">
            Reject Request
          </a>
        </div>

        <p style="font-size: 12px; color: #6b7280; margin-top: 30px;">
          This email was generated by RequestFlow Tracker.
        </p>
      </div>
    </div>
  </div>
`,
  });
};

module.exports = {
  sendApprovalEmail,
};
